services:
  app:
    build: .
    container_name: service-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./prisma/data:/app/prisma/data:z
      - ./public/uploads:/app/public/uploads:z
      - ./public/archives:/app/public/archives:z
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: service-redis
    restart: always
