services:
  app:
    build: .
    container_name: service-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:///app/prisma/data/dev.db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    volumes:
      - ./prisma/data:/app/prisma/data:z
      - ./public/uploads:/app/public/uploads:z
      - ./public/archives:/app/public/archives:z
    depends_on:
      - redis
    restart: always

  socket:
    build: .
    container_name: service-socket
    command: node socket-server.js
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: service-redis
    restart: always
